name: slint Build

on:
  push:
    branches:
      - slint
  workflow_dispatch:
env:
  SLINT_BINARY_FEATURES: "-DSLINT_FEATURE_BACKEND_WINIT=ON -DSLINT_FEATURE_RENDERER_FEMTOVG=ON -DSLINT_FEATURE_RENDERER_SKIA=ON -DSLINT_FEATURE_RENDERER_SKIA_VULKAN=ON"
  LATEST_RELEASE: "v1.6.0"
jobs:
  slint-build:
    name: slint Build
    runs-on: windows-2022
    steps:
      # - name: Set Mingw64 Ninja
      #   run: |
      #     (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
      #     7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
      #     (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
      #     7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Package Directories
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/slint-ui/slint -b ${{ env.LATEST_RELEASE }} ; cd slint
          mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ env.SLINT_BINARY_FEATURES }} -DCMAKE_INSTALL_PREFIX=C:\slint_install -DBUILD_SHARED_LIBS=ON
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a slint_shared_latest_release.7z C:\slint_install
      - uses: actions/upload-artifact@v4
        with:
          name: slint_shared_latest_release
          path: slint_shared_latest_release.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z

