name: Flac Build

on:
  push:
    branches:
      - flac
jobs:
  flac-mingw64-latest-build:
    name: flac Latest MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/xiph/flac.git
          git clone --depth=1 https://github.com/xiph/ogg.git

      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\ogg ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/ogg_install
          ninja ; ninja install

          $env:Path = "C:\ogg_install\lib;C:\ogg_install\include;C:\ogg_install\bin;$env:Path"
          cd C:\flac ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DINSTALL_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX=C:/flac_install
          ninja ; ninja install

      - name: Package Directories
        run: |
          7z a flac_MinGW64_Static.7z C:\flac_install
      - uses: actions/upload-artifact@v3
        with:
          name: flac_MinGW64_Static
          path: flac_MinGW64_Static.7z

  flac-vc143-build:
    name: flac vc143 Build
    runs-on: windows-2022
    steps:
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/xiph/flac.git
          git clone --depth=1 https://github.com/xiph/ogg.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\ogg ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/ogg_install
          ninja ; ninja install

          $env:Path = "C:\ogg_install\lib;C:\ogg_install\include;C:\ogg_install\bin;$env:Path"
          cd C:\flac ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DINSTALL_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX=C:/flac_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a flac_VC143_Static.7z C:\flac_install
      - uses: actions/upload-artifact@v3
        with:
          name: flac_VC143_Static
          path: flac_VC143_Static.7z

  flac-vc143-dyn-build:
    name: flac vc143 Dyn Build
    runs-on: windows-2022
    steps:
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/xiph/flac.git
          git clone --depth=1 https://github.com/xiph/ogg.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\ogg ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/ogg_install
          ninja ; ninja install

          $env:Path = "C:\ogg_install\lib;C:\ogg_install\include;C:\ogg_install\bin;$env:Path"
          cd C:\flac ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DINSTALL_MANPAGES=OFF -DBUILD_DOCS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/flac_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a flac_VC143_Dyn.7z C:\flac_install
      - uses: actions/upload-artifact@v3
        with:
          name: flac_VC143_Dyn
          path: flac_VC143_Dyn.7z