name: skia Build

on:
  push:
    branches:
      - skia
jobs:
  skia-vcpkg-latest-build:
    name: skia Latest Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
          # ls
          (new-object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/axojhf/cpp_library_build/skia/portfile.cmake','C:\portfile.cmake')
          # ls
          mv C:\portfile.cmake C:\vcpkg\ports\skia\portfile.cmake -Force
          .\vcpkg install skia[direct3d,vulkan]:x64-windows