name: skia Build

on:
  push:
    branches:
      - skia
jobs:
  # skia-vcpkg-latest-build:
  #   name: skia Latest Build
  #   runs-on: windows-2022
  #   steps:
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     # - name: Install Vulkan SDK
  #     #   uses: humbletim/install-vulkan-sdk@v1.1.1
  #     #   with:
  #     #     version: latest
  #     #     cache: true
  #     - name: Build
  #       run: |
  #         cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
  #         # ls
  #         (new-object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/axojhf/cpp_library_build/skia/portfile.cmake','C:\portfile.cmake')
  #         # ls
  #         mv C:\portfile.cmake C:\vcpkg\ports\skia\portfile.cmake -Force
  #         # .\vcpkg install skia[direct3d,vulkan]:x64-windows
  #         .\vcpkg install skia:x64-windows

  skia-vcpkg-cache-latest-build:
    name: skia cache Latest Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true
      - name: Cache Local64
        uses: actions/cache@v3
        with:
          key: skai-deps-vcpkg
          path: |
            C:/vcpkg/installed
      - name: Build
        # continue-on-error: true
        run: |
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
          (new-object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/axojhf/cpp_library_build/skia/portfile.cmake','C:\portfile.cmake')
          mv C:\portfile.cmake C:\vcpkg\ports\skia\portfile.cmake -Force
          .\vcpkg install skia[direct3d,vulkan]:x64-windows
          # .\vcpkg install skia:x64-windows
          Write-Host "output build-x64-windows-dbg-out.log\n" -ForegroundColor Green
          cat C:\vcpkg\buildtrees\skia\build-x64-windows-dbg-out.log
          Write-Host "output build-x64-windows-dbg-err.log\n" -ForegroundColor Green
          cat C:\vcpkg\buildtrees\skia\build-x64-windows-dbg-err.log
      - name: Package Directories
        run: |
          7z a skia_vcpkg_x64_windows_latest_build.7z C:/vcpkg/installed/x64-windows
      - uses: actions/upload-artifact@v3
        with:
          name: skia_vcpkg_x64_windows_latest_build
          path: skia_vcpkg_x64_windows_latest_build.7z

  # cache-build:
  #   name: Cache Build
  #   runs-on: windows-2022
  #   steps:
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Cache Local64
  #       uses: actions/cache@v3
  #       with:
  #         key: skai-deps-vcpkg
  #         path: |
  #           C:/vcpkg/installed
  #     - name: Build
  #       run: |
  #         cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
  #         .\vcpkg install brotli[core]:x64-windows bzip2[core,tool]:x64-windows egl-registry[core]:x64-windows expat[core]:x64-windows freetype[brotli,bzip2,core,png,zlib]:x64-windows harfbuzz[core]:x64-windows icu[core,tools]:x64-windows libjpeg-turbo[core]:x64-windows libpng[core]:x64-windows libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows opengl[core]:x64-windows opengl-registry[core]:x64-windows pkgconf[core]:x64-windows vcpkg-cmake[core]:x64-windows vcpkg-cmake-config[core]:x64-windows vcpkg-cmake-get-vars[core]:x64-windows vcpkg-gn[core]:x64-windows vcpkg-pkgconfig-get-modules[core]:x64-windows vcpkg-tool-gn[core]:x64-windows vcpkg-tool-meson[core]:x64-windows zlib[core]:x64-windows --clean-after-build
