name: protopuf Build

on:
  push:
    branches:
      - protopuf
jobs:
  protopuf-mingw64-build:
    name: protopuf MinGW64 Build
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v3
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/PragmaTwice/protopuf.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install protobuf:x64-mingw-static
          cd C:\protopuf ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/protopuf_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a protopuf_MinGW64_Static.7z C:\protopuf_install
      - uses: actions/upload-artifact@v3
        with:
          name: protopuf_MinGW64_Static
          path: protopuf_MinGW64_Static.7z

  protopuf-vc143-static-build:
    name: protopuf vc143 Static Build
    runs-on: windows-2022
    steps:
      # - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/PragmaTwice/protopuf.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install protobuf:x64-windows-static
          cd C:\protopuf ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/protopuf_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a protopuf_VC143_Static.7z C:\protopuf_install
      - uses: actions/upload-artifact@v3
        with:
          name: protopuf_VC143_Static
          path: protopuf_VC143_Static.7z

  protopuf-vc143-dyn-build:
    name: protopuf vc143 Dynamic Build
    runs-on: windows-2022
    steps:
      # - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/PragmaTwice/protopuf.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install protobuf:x64-windows
          cd C:\protopuf ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=C:/protopuf_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a protopuf_VC143_Dyn.7z C:\protopuf_install
      - uses: actions/upload-artifact@v3
        with:
          name: protopuf_VC143_Dyn
          path: protopuf_VC143_Dyn.7z