name: librf Build

on:
  push:
    branches:
      - librf
jobs:
  librf-mingw64-build:
    name: librf MinGW64 Build
    runs-on: windows-latest
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/tearshark/librf.git -b 3.0.0
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:/librf ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DLIBRF_DYNAMIC_LIBRARY=OFF -DCMAKE_INSTALL_PREFIX=C:\librf_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a librf_MinGW64_Static.7z C:\librf_install
      - uses: actions/upload-artifact@v3
        with:
          name: librf_MinGW64_Static
          path: librf_MinGW64_Static.7z

  librf-vc143-build:
    name: librf vc143 Build
    runs-on: windows-latest
    steps:
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/tearshark/librf.git -b 3.0.0
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:/librf ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DLIBRF_DYNAMIC_LIBRARY=OFF -DCMAKE_INSTALL_PREFIX=C:\librf_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a librf_VC143_Static.7z C:\librf_install
      - uses: actions/upload-artifact@v3
        with:
          name: librf_VC143_Static
          path: librf_VC143_Static.7z
