name: Coost Build

on:
  push:
    branches:
      - coost
jobs:
  coost-mingw64-build:
    name: Coost Vcpkg MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/axojhf/build_openssl/releases/download/build/openssl3_mingw_static.7z','openssl3.7z')
          7z x -aoa -oC:\ openssl3.7z
          rm openssl3.7z
          # 将C:\openssl3\lib64改名为C:\openssl3\lib
          mv C:\openssl3\lib64 C:\openssl3\lib
          cd C:/
          git clone --depth 1 https://github.com/idealvin/coost.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;C:\openssl3\lib;C:\openssl3\include;C:\openssl3\bin;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install curl[core,non-http,ssl,winssl,http2,brotli]:x64-mingw-static
          $env:Path = "C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          cd C:\coost
          mkdir build
          cd build
          cmake .. -DWITH_LIBCURL=ON -DWITH_OPENSSL=ON -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a coost_MinGW64_Static.7z C:\vcpkg\installed\x64-mingw-static\lib C:\vcpkg\installed\x64-mingw-static\include C:\coost\install
      - uses: actions/upload-artifact@v3
        with:
          name: coost_vcpkg_MinGW64_Static
          path: coost_MinGW64_Static.7z

  coost-mingw64-mini-build:
    name: Coost Vcpkg MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/idealvin/coost.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\coost
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a coost_mini_MinGW64_Static.7z C:\coost\install
      - uses: actions/upload-artifact@v3
        with:
          name: coost_mini_MinGW64_Static
          path: coost_mini_MinGW64_Static.7z

  coost-vc143-build:
    name: Coost Vcpkg vc143 Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/axojhf/build_openssl/releases/download/build/openssl3_vc143_static.7z','openssl3.7z')
          7z x -aoa -oC:\ openssl3.7z
          rm openssl3.7z
          cd C:/
          git clone --depth 1 https://github.com/idealvin/coost.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;C:\openssl3\lib;C:\openssl3\include;C:\openssl3\bin;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install curl[core,non-http,ssl,winssl,http2,brotli]:x64-windows-static
          $env:Path = "C:\vcpkg\installed\x64-windows-static\lib;C:\vcpkg\installed\x64-windows-static\include;$env:Path"
          cd C:\coost
          mkdir build
          cd build
          cmake .. -DWITH_LIBCURL=ON -DWITH_OPENSSL=ON -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a coost_VC143_Static.7z C:\vcpkg\installed\x64-windows-static\lib C:\vcpkg\installed\x64-windows-static\include C:\coost\install
      - uses: actions/upload-artifact@v3
        with:
          name: coost_vcpkg_VC143_Static
          path: coost_VC143_Static.7z

  coost-vc143-mini-build:
    name: Coost vc143 mini Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/idealvin/coost.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\coost
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a coost_VC143_mini_Static.7z C:\coost\install
      - uses: actions/upload-artifact@v3
        with:
          name: coost_VC143_mini_Static
          path: coost_VC143_mini_Static.7z