name: Taichi Build

on:
  push:
    branches:
      - taichi
jobs:
  # taichi-mingw64-latest-build:
  #   name: taichi Latest MinGW64 Build
  #   runs-on: windows-2019
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
  #         7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
  #         cd C:\ ; git clone --depth=1 https://github.com/taichi-dev/taichi.git

  #     - name: Build
  #       run: |
  #         $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
  #         cd C:\ogg ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/ogg_install
  #         ninja ; ninja install

  #         $env:Path = "C:\ogg_install\lib;C:\ogg_install\include;C:\ogg_install\bin;$env:Path"
  #         cd C:\taichi ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DINSTALL_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX=C:/taichi_install
  #         ninja ; ninja install

  #     - name: Package Directories
  #       run: |
  #         7z a taichi_MinGW64_Static.7z C:\taichi_install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: taichi_MinGW64_Static
  #         path: taichi_MinGW64_Static.7z

  taichi-vc143-build:
    name: taichi vc143 Build
    runs-on: windows-2022
    steps:
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/taichi-dev/taichi.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build
        env:
          PY: 3.11
          PROJECT_NAME: taichi-cp311
          TAICHI_CMAKE_ARGS: >-
            -DTI_WITH_OPENGL:BOOL=ON
            -DTI_WITH_VULKAN:BOOL=ON
            -DTI_WITH_DX11:BOOL=ON
            -DTI_WITH_DX12:BOOL=ON
            -DTI_WITH_CC:BOOL=OFF
            -DTI_BUILD_TESTS:BOOL=ON
            -DTI_WITH_C_API=ON
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\taichi
          python .\.github\workflows\scripts\build.py
      # - name: Package Directories
      #   run: |
      #     7z a taichi_VC143_Static.7z C:\taichi_install
      - uses: actions/upload-artifact@v3
        with:
          name: taichi_vc143
          path: C:/taichi/dist/*.whl

  # taichi-vc143-dyn-build:
  #   name: taichi vc143 Dyn Build
  #   runs-on: windows-2022
  #   steps:
  #     - name: Set Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
  #         cd C:\ ; git clone --depth=1 https://github.com/xiph/taichi.git
  #         git clone --depth=1 https://github.com/xiph/ogg.git
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build
  #       run: |
  #         $env:Path = "C:\ninja;$env:Path"
  #         cd C:\ogg ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/ogg_install
  #         ninja ; ninja install

  #         $env:Path = "C:\ogg_install\lib;C:\ogg_install\include;C:\ogg_install\bin;$env:Path"
  #         cd C:\taichi ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DINSTALL_MANPAGES=OFF -DBUILD_DOCS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/taichi_install
  #         ninja ; ninja install
  #     - name: Package Directories
  #       run: |
  #         7z a taichi_VC143_Dyn.7z C:\taichi_install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: taichi_VC143_Dyn
  #         path: taichi_VC143_Dyn.7z