name: FFTW3 Build

on:
  push:
    branches:
      - main
jobs:
  fftw-mingw64-build:
    name: FFTW3 MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          del mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          del ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.fftw.org/fftw-3.3.10.tar.gz','fftw-3.3.10.tar.gz')
          7z x -aoa fftw-3.3.10.tar.gz
          7z x -aoa -oC:\ fftw-3.3.10.tar
          del fftw-3.3.10.tar.gz
          del fftw-3.3.10.tar
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
      - shell: msys2 {0}
        run: |
          # pacman -S --noconfirm git ninja
          export PATH="/c/mingw64/bin:/c/ninja:$PATH"
          cd /c/fftw-3.3.10
          ls
          ./configure --prefix=/c/FFTW --enable-shared=no --enable-static=yes --enable-threads --enable-sse2 --enable-avx --enable-avx2
          mingw32-make -j
          mingw32-make install
      - name: Package Directories
        run: |
          7z a FFTW_MinGW64_Static.7z C:\FFTW
      - uses: actions/upload-artifact@v3
        with:
          name: FFTW_MinGW64_Static
          path: FFTW_MinGW64_Static.7z

  libsndfile-mingw64-build:
    name: libsndfile MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/libsndfile/libsndfile/archive/refs/tags/1.1.0.zip','libsndfile-1.1.0.zip')
          7z x -aoa -oC:\ libsndfile-1.1.0.zip
          rm libsndfile-1.1.0.zip
      - name: Build
        run: |
          # $env:Path = "C:\mingw64\bin;C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;$env:Path"
          # $env:Path = "C:\openssl-1.1\x64\lib;C:\openssl-1.1\x64\include;C:\mingw64\bin;C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;C:\Strawberry\perl\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\Program Files\PowerShell\7;C:\Program Files\CMake\bin;C:\Windows\System32\WindowsPowerShell\v1.0"
          $env:Path = "C:\mingw64\bin;C:\ninja;C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          vcpkg install libogg:x64-mingw-static libvorbis:x64-mingw-static libflac:x64-mingw-static opus:x64-mingw-static mp3lame:x64-mingw-static mpg123:x64-mingw-static
          cd C:\libsndfile-1.1.0
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\libsndfile -DBUILD_EXAMPLES=OFF
          ninja
          ninja install
      - name: Package Directories
        run: |
          7z a libsndfile_MinGW64_Static.7z C:\libsndfile
      - uses: actions/upload-artifact@v3
        with:
          name: libsndfile_MinGW64_Static
          path: libsndfile_MinGW64_Static.7z
