name: librclone Build

on:
  push:
    branches:
      - librclone
jobs:
  librclone-build:
    name: librclone Build
    runs-on: windows-latest
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.0/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          path-type: inherit
      - shell: msys2 {0}
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-gcc
          export PATH="/c/ninja:$PATH"
          cd /c/
          git clone --depth=1 https://github.com/rclone/rclone
          cd rclone/librclone
          go build --buildmode=c-shared -o librclone.dll
          ls
      - name: Package Directories
        run: |
          mkdir librclone
          cp C:\rclone\librclone\librclone.dll C:\librclone -Force
          cp C:\rclone\librclone\librclone.h C:\librclone -Force
          7z a librclone.7z C:\librclone
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: cpr_MinGW64_Static
      #     path: cpr_MinGW64_Static.7z
      - name: Update librclone Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: librclone-build
          files: |
            librclone.7z

