name: async_simple Build

on:
  push:
    branches:
      - async_simple
jobs:
  async_simple-mingw64-build:
    name: async_simple MinGW64 Build
    runs-on: windows-latest
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/alibaba/async_simple.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:/async_simple ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\async_simple_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a async_simple_MinGW64_Static.7z C:\async_simple_install
      - uses: actions/upload-artifact@v3
        with:
          name: async_simple_MinGW64_Static
          path: async_simple_MinGW64_Static.7z

  async_simple-vc143-build:
    name: async_simple vc143 Build
    runs-on: windows-latest
    steps:
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:/
          git clone --depth 1 https://github.com/alibaba/async_simple.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:/async_simple ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\async_simple_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a async_simple_VC143_Static.7z C:\async_simple_install
      - uses: actions/upload-artifact@v3
        with:
          name: async_simple_VC143_Static
          path: async_simple_VC143_Static.7z
