name: skia Build

on:
  push:
    branches:
      - skia
jobs:
  skia-vcpkg-latest-build:
    name: skia Latest Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          cp portfile.cmake C:\portfile.cmake
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
          cp C:\portfile.cmake C:\vcpkg\ports\skia\portfile.cmake
          .\vcpkg install skia[direct3d,vulkan]:x64-windows