name: MsQuic Build

on:
  push:
    branches:
      - msquic
jobs:
  msquic-mingw64-build:
    name: MsQuic MinGW64 Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:\
          git clone --depth=1 https://github.com/microsoft/msquic.git -b v2.1.7
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\msquic ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DQUIC_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=C:/MsQuic
          ninja
          ninja install
      - name: Package Directories
        run: |
          7z a MsQuic_MinGW64_Static.7z C:\MsQuic
      - uses: actions/upload-artifact@v3
        with:
          name: MsQuic_MinGW64_Static
          path: MsQuic_MinGW64_Static.7z

  msquic-vc143-static-build:
    name: MsQuic vc143 Static Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:\
          git clone --depth=1 https://github.com/microsoft/msquic.git -b v2.1.7
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\msquic ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DQUIC_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=C:/MsQuic
          ninja
          ninja install
      - name: Package Directories
        run: |
          7z a MsQuic_VC143_Static.7z C:\MsQuic
      - uses: actions/upload-artifact@v3
        with:
          name: MsQuic_VC143_Static
          path: MsQuic_VC143_Static.7z

  msquic-vc143-dyn-build:
    name: MsQuic vc143 Dynamic Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:\
          git clone --depth=1 https://github.com/microsoft/msquic.git -b v2.1.7
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\msquic ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DQUIC_BUILD_SHARED=ON -DCMAKE_INSTALL_PREFIX=C:/MsQuic
          ninja
          ninja install
      - name: Package Directories
        run: |
          7z a MsQuic_VC143_Dyn.7z C:\MsQuic
      - uses: actions/upload-artifact@v3
        with:
          name: MsQuic_VC143_Dyn
          path: MsQuic_VC143_Dyn.7z