name: FFTW3 Build

on:
  push:
    branches:
      - coost
jobs:
  coost-mingw64-build:
    name: FFTW3 Vcpkg MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install coost[libcurl,openssl]:x64-mingw-static
      - name: Package Directories
        run: |
          7z a coost_MinGW64_Static.7z C:\vcpkg\installed\x64-mingw-static\lib C:\vcpkg\installed\x64-mingw-static\include
      - uses: actions/upload-artifact@v3
        with:
          name: coost_vcpkg_MinGW64_Static
          path: coost_MinGW64_Static.7z