name: Protobuf Build

on:
  push:
    branches:
      - protobuf
jobs:
  coost-mingw64-build:
    name: Protobuf Vcpkg MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.zip','protobuf.zip')
          7z x -aoa -oC:\ protobuf.zip
          rm protobuf.zip
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install zlib:x64-mingw-static
          $env:Path = "C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          cd C:\protobuf-3.21.12
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\protobuf -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=ON -DBUILD_SHARED_LIBS=OFF
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a protobuf_MinGW64_Static.7z C:\protobuf
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf_MinGW64_Static
          path: protobuf_MinGW64_Static.7z

  coost-mingw64-dyn-build:
    name: Protobuf Vcpkg MinGW64 Dynamic Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.zip','protobuf.zip')
          7z x -aoa -oC:\ protobuf.zip
          rm protobuf.zip
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install zlib:x64-mingw-static
          $env:Path = "C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          cd C:\protobuf-3.21.12
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\protobuf -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=ON -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a protobuf_MinGW64_Dynamic.7z C:\protobuf
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf_MinGW64_Dynamic
          path: protobuf_MinGW64_Dynamic.7z

  coost-vc143-build:
    name: Coost Vcpkg vc143 Static Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.zip','protobuf.zip')
          7z x -aoa -oC:\ protobuf.zip
          rm protobuf.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install zlib:x64-windows-static
          $env:Path = "C:\vcpkg\installed\x64-windows-static\lib;C:\vcpkg\installed\x64-windows-static\include;$env:Path"
          cd C:\protobuf-3.21.12
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\protobuf -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=ON -DBUILD_SHARED_LIBS=OFF
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a protobuf_VC143_Static.7z C:\protobuf
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf_VC143_Static
          path: protobuf_VC143_Static.7z

  coost-vc143-dyn-build:
    name: Coost Vcpkg vc143 Dynamic Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.zip','protobuf.zip')
          7z x -aoa -oC:\ protobuf.zip
          rm protobuf.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          vcpkg install zlib:x64-windows-static
          $env:Path = "C:\vcpkg\installed\x64-windows-static\lib;C:\vcpkg\installed\x64-windows-static\include;$env:Path"
          cd C:\protobuf-3.21.12
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\protobuf -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB=ON -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          7z a protobuf_VC143_Dynamic.7z C:\protobuf
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf_VC143_Dynamic
          path: protobuf_VC143_Dynamic.7z