name: FFTW3 Build

on:
  push:
    branches:
      - wolfssl
jobs:
  wolfssl-mingw64-static-build:
    name: wolfssl static MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip','nasm.zip')
          7z x -aoa -oC:\ nasm.zip ; rm nasm.zip
          cd C:\ ; git clone --depth=1 --recursive https://github.com/wolfSSL/wolfssl.git -b v5.6.0-stable
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;C:\nasm-2.16.01;$env:Path"
          cd C:\wolfssl ; mkdir build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\wolfssl_install -DWOLFSSL_SESSION_TICKET=ON -DWOLFSSL_PSK=ON
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a wolfssl_MinGW64_Static.7z C:\wolfssl_install
      - uses: actions/upload-artifact@v3
        with:
          name: wolfssl_MinGW64_Static
          path: wolfssl_MinGW64_Static.7z