name: Cpr Build

on:
  push:
    branches:
      - cpr
jobs:
  # cpr-mingw64-build:
  #   name: Cpr Vcpkg MinGW64 Build
  #   runs-on: windows-2019
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
  #         7z x -aoa -oC:\ mingw64.7z
  #         rm mingw64.7z
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #     - name: Build
  #       run: |
  #         $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
  #         cd C:\vcpkg
  #         git pull
  #         ./bootstrap-vcpkg.bat
  #         vcpkg install curl[non-http,ssl,http2,schannel]:x64-mingw-static cpr:x64-mingw-static
  #     - name: Package Directories
  #       run: |
  #         # 7z a cpr_MinGW64_Static.7z C:\vcpkg\installed\x64-mingw-static\lib C:\vcpkg\installed\x64-mingw-static\include
  #         vcpkg export curl:x64-mingw-static cpr:x64-mingw-static nghttp2:x64-mingw-static zlib:x64-mingw-static --7zip --output=cpr_MinGW64_Static
  #         ls
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: cpr_MinGW64_Static
  #         path: C:\vcpkg\cpr_MinGW64_Static.7z

  coost-mingw64-latest-build:
    name: Cpr Latest MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/axojhf/build_openssl/releases/download/build/openssl3_mingw_static.7z','openssl3.7z')
          7z x -aoa -oC:\ openssl3.7z
          rm openssl3.7z
          mv C:\openssl3\lib64 C:\openssl3\lib
          (new-object System.Net.WebClient).DownloadFile('https://curl.se/download/curl-7.87.0.zip','curl.zip')
          7z x -aoa -oC:\ curl.zip
          rm curl.zip
          cd C:/
          # git clone --depth 1 https://github.com/axojhf/cpr.git -b mod
          git clone --depth 1 https://github.com/libcpr/cpr.git
          git clone --depth 1 https://github.com/google/brotli.git
          git clone --depth 1 https://github.com/nibanks/msh3.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\vcpkg
          git pull
          ./bootstrap-vcpkg.bat
          # libssh2:x64-mingw-static
          vcpkg install zstd:x64-mingw-static zlib:x64-mingw-static nghttp2:x64-mingw-static
          
          cd C:/brotli
          mkdir build_mingw64
          cd build_mingw64
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\brotli_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja
          ninja install
          
          $env:Path = "C:\msh3_install;C:\msh3_install\include;C:\msh3_install\lib;C:\brotli_install\include;C:\brotli_install\lib;C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          cd C:/curl-7.87.0
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF -DCURL_USE_SCHANNEL=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/curl -DCURL_USE_LIBSSH2=OFF -DCURL_BROTLI=ON -DCURL_ZSTD=ON -DUSE_NGHTTP2=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja
          ninja install
          
          cd C:/cpr
          mkdir build
          cd build
          $env:Path = "C:\curl;C:\curl\lib;C:\curl\include;$env:Path"
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCPR_USE_SYSTEM_CURL=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/cpr_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCURL_LIBRARY=C:/curl/lib/libcurl.a -DCURL_INCLUDE_DIR=C:/curl/include
          ninja
          ninja install

      - name: Package Directories
        run: |
          7z a cpr_latest_MinGW64_Static.7z C:\curl C:\cpr_install C:\brotli_install
      - uses: actions/upload-artifact@v3
        with:
          name: cpr_latest_MinGW64_Static
          path: cpr_latest_MinGW64_Static.7z

  # coost-vc143-build:
  #   name: Coost Vcpkg vc143 Build
  #   runs-on: windows-2022
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/axojhf/build_openssl/releases/download/build/openssl3_vc143_static.7z','openssl3.7z')
  #         7z x -aoa -oC:\ openssl3.7z
  #         rm openssl3.7z
  #         cd C:/
  #         git clone --depth 1 https://github.com/idealvin/coost.git
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build
  #       run: |
  #         $env:Path = "C:\ninja;C:\openssl3\lib;C:\openssl3\include;C:\openssl3\bin;$env:Path"
  #         cd C:\vcpkg
  #         git pull
  #         ./bootstrap-vcpkg.bat
  #         vcpkg install curl[core,non-http,ssl,winssl,http2,brotli]:x64-windows-static
  #         $env:Path = "C:\vcpkg\installed\x64-windows-static\lib;C:\vcpkg\installed\x64-windows-static\include;$env:Path"
  #         cd C:\coost
  #         mkdir build
  #         cd build
  #         cmake .. -DWITH_LIBCURL=ON -DWITH_OPENSSL=ON -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
  #         cmake --build . --config Release
  #         cmake --install . --config Release
  #     - name: Package Directories
  #       run: |
  #         7z a coost_VC143_Static.7z C:\vcpkg\installed\x64-windows-static\lib C:\vcpkg\installed\x64-windows-static\include C:\coost\install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: coost_vcpkg_VC143_Static
  #         path: coost_VC143_Static.7z

  # coost-vc143-mini-build:
  #   name: Coost vc143 mini Build
  #   runs-on: windows-2022
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #         cd C:/
  #         git clone --depth 1 https://github.com/idealvin/coost.git
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build
  #       run: |
  #         $env:Path = "C:\ninja;$env:Path"
  #         cd C:\coost
  #         mkdir build
  #         cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\coost\install
  #         cmake --build . --config Release
  #         cmake --install . --config Release
  #     - name: Package Directories
  #       run: |
  #         7z a coost_VC143_mini_Static.7z C:\coost\install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: coost_VC143_mini_Static
  #         path: coost_VC143_mini_Static.7z