name: librclone Build

on:
  push:
    branches:
      - librclone
jobs:
  librclone-build:
    name: librclone Build
    runs-on: windows-latest
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.0/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          path-type: inherit
      - shell: msys2 {0}
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-gcc
          export PATH="/c/ninja:$PATH"
          cd /c/
          git clone --depth=1 https://github.com/rclone/rclone
          cd rclone/librclone
          go build --buildmode=c-shared -o librclone.dll
          ls
      # - name: Package Directories
      #   run: |
      #     cp -r C:\curl_install\lib C:\cpr_install -Force
      #     cp -r C:\curl_install\include C:\cpr_install -Force
      #     7z a cpr_MinGW64_Static.7z C:\cpr_install
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: cpr_MinGW64_Static
      #     path: cpr_MinGW64_Static.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z

