name: Boost Build

on:
  push:
    branches:
      - boost
jobs:
  boost-mingw64-build:
    name: Boost MinGW64 Static Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0_rc1.7z','boost.7z')
          7z x -aoa -oC:\ boost.7z
          rm boost.7z
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          # cd C:\vcpkg
          # git pull
          # ./bootstrap-vcpkg.bat
          # vcpkg install zlib:x64-mingw-static
          # $env:Path = "C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
          cd C:\boost_1_81_0
          ./bootstrap.bat
          ./b2 toolset=gcc --build-dir="C:\boost_1_81_0\build" --prefix="C:\boost" --address-model=64 --architecture=x86 --link=static --runtime-link=static --threading=multi --variant=release install
      - name: Package Directories
        run: |
          7z a boost_MinGW64_Static.7z C:\boost
      - uses: actions/upload-artifact@v3
        with:
          name: boost_MinGW64_Static
          path: boost_MinGW64_Static.7z

  boost-mingw64-dyn-build:
    name: Boost MinGW64 Dynamic Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0_rc1.7z','boost.7z')
          7z x -aoa -oC:\ boost.7z
          rm boost.7z
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\boost_1_81_0
          ./bootstrap.bat
          ./b2 toolset=gcc --build-dir="C:\boost_1_81_0\build" --prefix="C:\boost" --address-model=64 --architecture=x86 --link=shared --runtime-link=shared --threading=multi --variant=release install
      - name: Package Directories
        run: |
          7z a protobuf_MinGW64_Dynamic.7z C:\protobuf
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf_MinGW64_Dynamic
          path: protobuf_MinGW64_Dynamic.7z

  boost-vc143-build:
    name: Boost VC143 Static Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0_rc1.7z','boost.7z')
          7z x -aoa -oC:\ boost.7z
          rm boost.7z
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\boost_1_81_0
          ./bootstrap.bat
          ./b2 toolset=msvc-14.3 --build-dir="C:\boost_1_81_0\build" --prefix="C:\boost" --address-model=64 --architecture=x86 --link=static --runtime-link=shared --threading=multi --variant=release install
      - name: Package Directories
        run: |
          7z a boost_VC143_Static.7z C:\boost
      - uses: actions/upload-artifact@v3
        with:
          name: boost_VC143_Static
          path: boost_VC143_Static.7z

  boost-vc143-dyn-build:
    name: Boost Vcpkg vc143 Dynamic Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0_rc1.7z','boost.7z')
          7z x -aoa -oC:\ boost.7z
          rm boost.7z
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\boost_1_81_0
          ./bootstrap.bat
          ./b2 toolset=msvc-14.3 --build-dir="C:\boost_1_81_0\build" --prefix="C:\boost" --address-model=64 --architecture=x86 --link=shared --runtime-link=shared --threading=multi --variant=release install
      - name: Package Directories
        run: |
          7z a boost_VC143_Dynamic.7z C:\boost
      - uses: actions/upload-artifact@v3
        with:
          name: boost_VC143_Dynamic
          path: boost_VC143_Dynamic.7z