name: Libhv Build

on:
  push:
    branches:
      - libhv
jobs:
  BuildMinGW64Static:
    runs-on: windows-2019
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/axojhf/build_openssl/releases/download/build/openssl3_mingw_static.7z','openssl3.7z')
          7z x -aoa -oC:\ openssl3.7z
          rm openssl3.7z
          # 将C:\openssl3\lib64改名为C:\openssl3\lib
          mv C:\openssl3\lib64 C:\openssl3\lib
          (new-object System.Net.WebClient).DownloadFile('https://github.com/nghttp2/nghttp2/releases/download/v1.51.0/nghttp2-1.51.0.tar.gz','nghttp2.tar.gz')
          7z x -aoa nghttp2.tar.gz
          7z x -aoa -oC:\ nghttp2.tar
          rm nghttp2.tar.gz
          rm nghttp2.tar
          (new-object System.Net.WebClient).DownloadFile('https://github.com/madler/zlib/releases/download/v1.2.13/zlib1213.zip','zlib.zip')
          7z x -aoa -oC:\ zlib.zip
          rm zlib.zip
          cd C:\
          git clone --depth=1 https://github.com/ithewei/libhv.git
      - shell: powershell
        run: |
          $env:PATH = "C:\mingw64\bin;C:\ninja;C:\openssl3\lib;C:\openssl3\include;C:\openssl3\bin;C:\Program Files\PowerShell\7;C:\Program Files\CMake\bin;C:\Windows\System32\WindowsPowerShell\v1.0"
          cd c:\zlib-1.2.13
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/zlib -DZLIB_COMPAT=ON -DBUILD_SHARED_LIBS=OFF
          cmake --build . --config Release
          cmake --install . --config Release
          rm C:/zlib/lib/libzlib.dll.a
          cp C:/zlib/lib/libzlibstatic.a C:/zlib/lib/libz.a

          $env:PATH = "C:\zlib\include;C:\zlib\lib;$env:PATH"

          cd c:\nghttp2-1.51.0
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/nghttp2 -DENABLE_STATIC_LIB=ON -DENABLE_SHARED_LIB=OFF -DENABLE_EXAMPLES=OFF
          cmake --build . --config Release
          cmake --install . --config Release

          cd c:\libhv
          mkdir 3rd
          # powershell复制C:/openssl3到C:\libhv\3rd
          cp -r C:/openssl3 C:\libhv\3rd
          cp -r C:/nghttp2 C:\libhv\3rd
          cp -r C:/zlib C:\libhv\3rd
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:/libhv/install -DENABLE_STATIC_LIB=ON -DENABLE_SHARED_LIB=OFF -DENABLE_EXAMPLES=OFF -DENABLE_TESTS=OFF -DENABLE_OPENSSL=ON -DENABLE_ZLIB=ON -DENABLE_NGHTTP2=ON
          cmake --build . --config Release
          cmake --install . --config Release
      - name: Package Directories
        run: |
          #使用7z将C:\libhv\install目录打包为libhv.7z
          7z a libhv.7z C:\libhv\install
      - uses: actions/upload-artifact@v3
        with:
          name: Libhv MinGW64
          path: libhv.7z