name: daScript Build

on:
  push:
    branches:
      - daScript
jobs:
  build:
    name: daScript Build
    runs-on: windows-2022
    steps:
      # - name: Set Mingw64 Ninja
      #   run: |
      #     (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
      #     7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
      #     (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
      #     7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          cd C:\ ; git clone --depth=1 https://github.com/GaijinEntertainment/daScript ; cd daScript
          mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\daScriptInstall -DDAS_AOT_EXAMPLES_DISABLED=ON -DDAS_TUTORIAL_DISABLED=ON
          ninja
          ninja install
      - name: Package Directories
        run: |
          cp -r C:\daScript\bin C:\daScriptInstall -Force
          # cp -r C:\curl_install\include C:\cpr_install -Force
          7z a daScript_VC143.7z C:\daScriptInstall
      - uses: actions/upload-artifact@v3
        with:
          name: daScript_VC143
          path: daScript_VC143.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z

