name: OpenCC Build

on:
  push:
    branches:
      - opencc
jobs:
  opencc-custom-cpp20-mingw64-build:
    name: OpenCC Custom C++20 MinGW64 Static Build
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v3
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/axojhf/OpenCC.git -b cpp20
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\OpenCC ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/opencc_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCC_MinGW64_Static_Custom.7z C:\opencc_install
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCC_MinGW64_Static_Custom_cpp20
          path: OpenCC_MinGW64_Static_Custom.7z

  opencc-custom-mingw64-build:
    name: OpenCC Custom MinGW64 Static Build
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v3
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/axojhf/OpenCC.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\OpenCC ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/opencc_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCC_MinGW64_Static_Custom.7z C:\opencc_install
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCC_MinGW64_Static_Custom
          path: OpenCC_MinGW64_Static_Custom.7z
  
  opencc-mingw64-build:
    name: OpenCC MinGW64 Static Build
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v3
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/BYVoid/OpenCC.git
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:\OpenCC ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/opencc_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCC_MinGW64_Static.7z C:\opencc_install
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCC_MinGW64_Static
          path: OpenCC_MinGW64_Static.7z

  opencc-vc143-static-build:
    name: OpenCC vc143 Static Build
    runs-on: windows-2022
    steps:
      # - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/BYVoid/OpenCC.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\OpenCC ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/opencc_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCC_VC143_Static.7z C:\opencc_install
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCC_VC143_Static
          path: OpenCC_VC143_Static.7z

  opencc-vc143-dyn-build:
    name: OpenCC vc143 Dynamic Build
    runs-on: windows-2022
    steps:
      # - uses: actions/checkout@v3
      - name: Set Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/BYVoid/OpenCC.git
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;$env:Path"
          cd C:\OpenCC ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/opencc_install
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCC_VC143_Dyn.7z C:\opencc_install
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCC_VC143_Dyn
          path: OpenCC_VC143_Dyn.7z