name: OpenCV Build

on:
  push:
    branches:
      - opencv
jobs:
  opencv-mingw64-build:
    name: OpenCV MinGW64 Build
    runs-on: windows-latest
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
      - name: Build
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:/vcpkg ; ./bootstrap-vcpkg.bat ; git pull ;./vcpkg.exe install opencv[eigen,ffmpeg,freetype,nonfree,opengl,openmp,world]:x64-mingw-static
          # cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\libcopp_install
          # ninja ; ninja install
      - name: Package Directories
        run: |
          7z a OpenCV_MinGW64_Static.7z C:\vcpkg\installed\x64-mingw-static
      - uses: actions/upload-artifact@v3
        with:
          name: OpenCV_MinGW64_Static
          path: OpenCV_MinGW64_Static.7z

  # opencv-vc143-build:
  #   name: OpenCV vc143 Build
  #   runs-on: windows-latest
  #   steps:
  #     - name: Set Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #         cd C:/
  #         git clone --depth 1 https://github.com/owent/libcopp.git -b v2
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build
  #       run: |
  #         $env:Path = "C:\ninja;$env:Path"
  #         cd C:/libcopp ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\libcopp_install
  #         ninja ; ninja install
  #     - name: Package Directories
  #       run: |
  #         7z a libcopp_VC143_Static.7z C:\libcopp_install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: libcopp_VC143_Static
  #         path: libcopp_VC143_Static.7z
