name: imgui_manual Build

on:
  push:
    branches:
      - imgui_manual
jobs:

  # imgui_manual-mingw64-latest-build:
  #   name: imgui_manual Latest MinGW64 Build
  #   runs-on: windows-2019
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
  #         7z x -aoa -oC:\ mingw64.7z
  #         rm mingw64.7z
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #         cd C:\ ; git clone --depth=1 https://github.com/pthom/imgui_manual.git
  #         git clone --depth=1 https://github.com/google/brotli.git

  #     - name: Build
  #       run: |
  #         $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
  #         cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install zstd:x64-mingw-static zlib:x64-mingw-static nghttp2:x64-mingw-static
          
  #         cd C:\brotli
  #         cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\brotli_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
  #         ninja ; ninja install
          
  #         $env:Path = "C:\brotli_install\lib;C:\brotli_install\include;C:\vcpkg\installed\x64-mingw-static\lib;C:\vcpkg\installed\x64-mingw-static\include;$env:Path"
  #         cd C:\imgui_manual ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_imgui_manual_EXE=OFF -DBUILD_TESTING=OFF -Dimgui_manual_USE_SCHANNEL=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/imgui_manual_install -Dimgui_manual_USE_LIBSSH2=OFF -Dimgui_manual_BROTLI=ON -Dimgui_manual_ZSTD=ON -DUSE_NGHTTP2=ON -DUSE_WEBSOCKETS=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
  #         ninja ; ninja install

  #     - name: Package Directories
  #       run: |
  #         # 复制C:\vcpkg\installed\x64-mingw-static\lib到C:\imgui_manual_install\lib，复制C:\vcpkg\installed\x64-mingw-static\include到C:\imgui_manual_install\include
  #         cp -r C:\vcpkg\installed\x64-mingw-static\lib C:\imgui_manual_install -Force
  #         cp -r C:\vcpkg\installed\x64-mingw-static\include C:\imgui_manual_install -Force
  #         cp -r C:\brotli_install\lib C:\imgui_manual_install -Force
  #         cp -r C:\brotli_install\include C:\imgui_manual_install -Force
  #         7z a imgui_manual_MinGW64_Static.7z C:\imgui_manual_install
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: imgui_manual_MinGW64_Static
  #         path: imgui_manual_MinGW64_Static.7z

  imgui_manual-vc143-build:
    name: imgui_manual Vcpkg vc143 Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          rm ninja-win.zip
          cd C:\ ; git clone --depth=1 https://github.com/pthom/imgui_manual.git
          cd C:\imgui_manual ; git submodule update --init --recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install glfw3:x64-windows-static sdl2:x64-windows-static

          $env:Path = "C:\ninja;C:\vcpkg\installed\x64-windows-static\lib;C:\vcpkg\installed\x64-windows-static\include;$env:Path"
          cd C:\imgui_manual ; mkdir build ; cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/imgui_manual_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          ninja ; ninja install
      - name: Package Directories
        run: |
          7z a imgui_manual_VC143_Static.7z C:\imgui_manual_install
      - uses: actions/upload-artifact@v3
        with:
          name: imgui_manual_VC143_Static
          path: imgui_manual_VC143_Static.7z

  # imgui_manual-vc143-dyn-build:
  #   name: imgui_manual vc143 Dyn Build
  #   runs-on: windows-2022
  #   steps:
  #     - name: Set Mingw64 Ninja
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
  #         7z x -aoa -oC:\ninja ninja-win.zip
  #         rm ninja-win.zip
  #         cd C:\ ; git clone --depth=1 https://github.com/imgui_manual/imgui_manual.git -b imgui_manual-7_88_1
  #         git clone --depth=1 https://github.com/google/brotli.git
  #     - uses: ilammy/msvc-dev-cmd@v1
  #       with:
  #         arch: amd64
  #         toolset: 14.3
  #     - name: Build
  #       run: |
  #         cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat ; vcpkg install zstd:x64-windows zlib:x64-windows nghttp2:x64-windows

  #         cd C:\brotli
  #         cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:\brotli_install -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
  #         ninja ; ninja install

  #         $env:Path = "C:\ninja;C:\brotli_install\lib;C:\brotli_install\include;C:\vcpkg\installed\x64-windows\lib;C:\vcpkg\installed\x64-windows\include;$env:Path"
  #         cd C:\imgui_manual ; mkdir build ; cd build
  #         cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_imgui_manual_EXE=OFF -DBUILD_TESTING=OFF -Dimgui_manual_USE_SCHANNEL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:/imgui_manual_install -Dimgui_manual_USE_LIBSSH2=OFF -Dimgui_manual_BROTLI=ON -Dimgui_manual_ZSTD=ON -DUSE_NGHTTP2=ON -DUSE_WEBSOCKETS=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
  #         ninja ; ninja install
  #     - name: Package Directories
  #       run: |
  #         cp -r C:\vcpkg\installed\x64-windows\lib C:\imgui_manual_install -Force
  #         cp -r C:\vcpkg\installed\x64-windows\include C:\imgui_manual_install -Force
  #         cp -r C:\brotli_install\lib C:\imgui_manual_install -Force
  #         cp -r C:\brotli_install\include C:\imgui_manual_install -Force
  #         7z a imgui_manual_VC143_Dyn.7z C:\imgui_manual
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: imgui_manual_VC143_Dyn
  #         path: imgui_manual_VC143_Dyn.7z