name: v8 Build

on:
  push:
    branches:
      - google-v8
jobs:
  v8-build:
    name: v8 Build
    runs-on: windows-2022
    steps:
      - name: Prepare Env
        run: |
          curl.exe -o depot_tools.zip https://storage.googleapis.com/chrome-infra/depot_tools.zip
          7z x -aoa -oC:\depot_tools depot_tools.zip ; rm depot_tools.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $env:Path = "C:\ninja;C:\depot_tools;$env:Path"
          $Env:DEPOT_TOOLS_WIN_TOOLCHAIN = 0
          mkdir C:\v8 ; cd C:\v8 ; gclient ; fetch --no-history v8; gclient sync
          cd v8
          python tools/dev/gm.py x64.release
          ls build ; ls out ; ls out\x64.release
      # - name: Package Directories
      #   run: |
      #     cp -r C:\curl_install\lib C:\cpr_install -Force
      #     cp -r C:\curl_install\include C:\cpr_install -Force
      #     7z a cpr_MinGW64_Static.7z C:\cpr_install
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cpr_MinGW64_Static
      #     path: cpr_MinGW64_Static.7z
      # - name: Update Cpr Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: cpr-build
      #     files: |
      #       cpr_MinGW64_Static.7z

