name: Cache

on:
  push:
    branches:
      - cache

jobs:
  fftw-vcpkg-mingw64-build:
    name: FFTW3 Vcpkg MinGW64 Build
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Cache Local64
        uses: actions/cache@v3
        with:
          key: skai-deps-vcpkg
          path: |
            C:/vcpkg
      - name: Build
        run: |
          cd C:\vcpkg ; git pull ; ./bootstrap-vcpkg.bat
          .\vcpkg install brotli[core]:x64-windows bzip2[core,tool]:x64-windows egl-registry[core]:x64-windows expat[core]:x64-windows freetype[brotli,bzip2,core,png,zlib]:x64-windows harfbuzz[core]:x64-windows icu[core,tools]:x64-windows libjpeg-turbo[core]:x64-windows libpng[core]:x64-windows libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows opengl[core]:x64-windows opengl-registry[core]:x64-windows pkgconf[core]:x64-windows vcpkg-cmake[core]:x64-windows vcpkg-cmake-config[core]:x64-windows vcpkg-cmake-get-vars[core]:x64-windows vcpkg-gn[core]:x64-windows vcpkg-pkgconfig-get-modules[core]:x64-windows vcpkg-tool-gn[core]:x64-windows vcpkg-tool-meson[core]:x64-windows zlib[core]:x64-windows --clean-after-build

          